version: "3.8"
services:
  database:
    image: mariadb
    volumes:
      - ./database-config.sql:/docker-entrypoint-initdb.d/database-config.sql
      - ~/docker/mariadb/etc/mysql/conf.d:/etc/mysql/conf.d:ro
      - ~/docker/mariadb/var/lib/mysql:/var/lib/mysql
      - ~/docker/mariadb/var/log/maria:/var/log/maria
    environment:
      - MARIADB_DATABASE=auth_db
      - MARIADB_ROOT_PASSWORD=0joker@
      - MARIADB_ROOT_HOST=%
      - MARIADB_USER=yechan
      - MARIADB_PASSWORD=0joker@
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - 3306:3306


  redis:
    image: redis
    command: redis-server --port 6379
    container_name: blacklist_cache
    hostname: blacklist_cache
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  application:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://database:3306/auth_db
      SPRING_DATASOURCE_USERNAME: yechan
      SPRING_DATASOURCE_PASSWORD: 0joker@
    ports:
      - 8080:8080
    depends_on:
      - database
      - redis