spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
  #    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379

#springdoc:
#  swagger-ui:
#    tags-sorter: alpha
#    operations-sorter: alpha
#    disable-swagger-default-url: true
#    display-request-duration: true
#  api-docs:
#    path: /api-docs/json
#  cache:
#    disabled: true
#  packages-to-scan: org.yechan.jwt

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    try-it-out-enabled: false
  packages-to-scan: org.yechan.jwt
  default-consumes-media-type: application/json
  default-produces-media-type: application/json